
GET http://localhost:5000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOm51bGwsImVtYWlsIjoicmFAZ21haWwuY29tIiwiaWF0IjoxNzAxNjkwNDc1LCJleHAiOjE3MDE2OTA0OTB9.rYvaNtKUlxtOxd5_tMpFVmIMpnpsF0FeDJKhKTlu-XA
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "nama": "fakhrir",
    "email": "ra@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ra@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout